all:
  vars:
    ansible_ssh_user: ubuntu
    domain: helloworld.com
  children:
    front-proxy:
      hosts:
        54.196.207.203

    nodes:
      hosts:
        3.85.210.80

    web:
      hosts:
        3.85.210.80