apiVersion: v1
kind: Service
metadata:
  name: service1
  labels:
    app: service1
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  selector:
    app: service1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    linkerd.io/inject: enabled
  name: service1
  labels:
    app: service1
spec:
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:                  
        - name: service1
          image: luccasbeltrame/service1
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example1
#  namespace: whois
  annotations:
  #  cert-manager.io/cluster-issuer: letsencrypt
    ingress.kubernetes.io/force-ssl-redirect: "false"
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: contour
  #  kubernetes.io/tls-acme: "true"
spec:
#  tls:
#  - secretName: service1
#    hosts:
#    - service1.xpto
  rules:
  - http:
      paths:
      - path: /service1
        backend:
          serviceName: service1
          servicePort: 8080 