apiVersion: v1
kind: Service
metadata:
  name: app-login
  labels:
    app: app-login
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3006
    targetPort: http
    protocol: TCP
  selector:
    app: app-login
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-login
  labels:
    app: app-login
spec:
  selector:
    matchLabels:
      app: app-login
  template:
    metadata:
      labels:
        app: app-login
    spec:
      containers:                  
        - name: app-login
          image: luccasbeltrame/app-login
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 3006
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: service2
  annotations:
  #  cert-manager.io/cluster-issuer: letsencrypt
    ingress.kubernetes.io/force-ssl-redirect: "false"
    kubernetes.io/ingress.class: contour
  #  kubernetes.io/tls-acme: "true"
spec:
#  tls:
#  - secretName: service2
#    hosts:
#    - service2.xpto
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: app-login
          servicePort: 3006            