- hosts: web
  gather_facts: False
  remote_user: ubuntu
  become: yes
  strategy: free
  become_user: root
  roles: 
    - { role: commons }
    - { role: onpremisses }

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        daemon_reload: yes
        state: restarted